Repository terasolunaorg/terasoluna-gfw-web-multi-blank, pull requests merged in 2018-03, with the labels that each got.

#409 [5.2.x] add doctype.#332
  projectName-env/src/main/resources/logback.xml
Labels: 5.2.2, improvement

#410 [5.1.x] add doctype.#332
  projectName-env/src/main/resources/logback.xml
Labels: 5.1.2, improvement

#412 update version for readme #411
  README.md
Labels: 5.5.0

#413 [5.4.x] update version for both readme and pom #411
  README.md
  pom.xml
  projectName-domain/pom.xml
  projectName-env/pom.xml
  projectName-initdb/pom.xml
  projectName-selenium/pom.xml
  projectName-web/pom.xml
Labels: 5.4.2

#414 [5.3.x] update version for both readme and pom #411
  README.md
  pom.xml
  projectName-domain/pom.xml
  projectName-env/pom.xml
  projectName-initdb/pom.xml
  projectName-selenium/pom.xml
  projectName-web/pom.xml
Labels: 5.3.3
