Repository terasolunaorg/terasoluna-gfw-web-multi-blank, pull requests merged in 2018-09, with the labels that each got.

#415 Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, type: improvement, version: 5.5.0

#426 [5.4.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.4.2

#427 [5.3.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.3.3

#428 [5.2.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.2.2

#429 [5.1.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.1.2

#430 [5.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 5.0.3

#431 [1.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #348
  projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
Labels: status: in-progress, version: 1.0.7

#432 add comment out the definition of password encoder #424
  pom.xml
  projectName-web/pom.xml
  projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
Labels: status: in-progress
