Repository terasolunaorg/terasoluna-gfw-web-multi-blank, pull requests merged in 2019-03, with the labels that each got.

#444 apply @ByteSize #443
  projectName-web/src/main/resources/ValidationMessages.properties
Labels: status: in-progress, type: new-feature, version: 5.5.1

#447 remove dependency of bcprov-jdk15on #424
  pom.xml
  projectName-domain/pom.xml
Labels: status: in-progress

#448 [5.4.x] apply @ByteSize #443
  projectName-web/src/main/resources/ValidationMessages.properties
Labels: status: in-progress, type: new-feature, version: 5.4.2
