Repository terasolunaorg/terasoluna-gfw-web-multi-blank, pull requests merged in 2019-05, with the labels that each got.

#458 remove a definition referring to Sonatype Nexus Snapshots #457
  pom.xml
Labels: version: 5.6.0

#463 remove a definition referring to Sonatype Nexus Snapshots #457 (#458)
  pom.xml
Labels: version: 5.5.1

#464 remove a definition referring to Sonatype Nexus Snapshots #457 (#458)
  pom.xml
Labels: version: 5.4.2

#461 [5.5.x]update relase version #459
  README.md
Labels: version: 5.5.1

#462 [5.4.x]update release version #459
  README.md
Labels: version: 5.4.2

#460 update relase version #459
  README.md
Labels: version: 5.6.0

#465 fix version to 5.5.1.RELEASE of README #459
  README.md
Labels: version: 5.6.0
